pipeline {
    agent any

    environment {
        IMAGE_NAME = "riya2704/myapp"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                dir('lab/exp7') {
                    sh 'docker build -t $IMAGE_NAME:latest .'
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-token', variable: 'DOCKER_TOKEN')]) {
                    sh '''
                        printenv DOCKER_TOKEN | docker login -u riya2704 --password-stdin
                    '''
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh 'docker push $IMAGE_NAME:latest'
            }
        }
    }
}